package api.model;

public enum CookieType {
    CAKE, GINGER_SNAP, CHOCOLATE_CHIP_COOKIE, DARK_CHOCOLATE, SUGAR_COOKIE, SANDWICH_COOKIE, BROWN_BUTTER_COOKIE,
    PEANUT_BUTTER_JELLY, BAVARIAN_CARAMEL, APRICOT_PISTACHIO, CINNAMON_ROLL
}
